export type TaskType =
  | "Manual"
  | "Purchase"
  | "Inventory"
  | "Event"
  | "Kitchen"
  | "Assignment"
  | "HR"
  | "System"
  | "Offering";

export type TaskStatus =
  | "Pending"
  | "In Progress"
  | "Blocked"
  | "Completed"
  | "Cancelled";

export type TaskPriority = "Low" | "Medium" | "High" | "Critical";

// Keep this aligned with modules you want to deep-link into.
export type LinkedModule =
  | "Manual"
  | "Inventory"
  | "Purchase"
  | "Event"
  | "Kitchen"
  | "Assignment"
  | "HR"
  | "System"
  | "ScheduledTemplate"
  | "Offering";

export interface Task {
  taskId: string;
  title: string;
  description: string;
  type: TaskType;
  linkedModule: LinkedModule;
  linkedId: string;
  priority: TaskPriority;
  status: TaskStatus;
  assignedTo: string;
  assignedBy: string;
  dueDate: string; // ISO date or datetime
  createdAt: string; // ISO datetime
  completedAt: string | null; // ISO datetime
  isAutoGenerated: boolean;
}

export type RecurrenceType = "Daily" | "Weekly" | "Monthly" | "Yearly";

export interface TaskTemplate {
  templateId: string;
  title: string;
  description: string;
  linkedModule: LinkedModule;
  priority: TaskPriority;
  defaultAssignee: string;
  recurrenceType: RecurrenceType;
  startDate: string; // ISO date
  endDate: string | null; // ISO date
  timeOfDay: string; // HH:mm
  isActive: boolean;
}

export type UserRole = "Admin" | "Finance" | "Store Manager" | "Event Manager";

export interface CurrentUser {
  userId: string;
  displayName: string;
  role: UserRole;
}

