import { useState } from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CheckCircle2, Zap, Link2 } from "lucide-react";
import TaskInlineDetail from "@/components/tasks/TaskInlineDetail";
import type { Task } from "@/modules/tasks/types";
import { taskSelectors, useCurrentUser, useTasks } from "@/modules/tasks/hooks";

const CompletedTasks = () => {
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const user = useCurrentUser();
  const tasksAll = useTasks();
  const tasks = tasksAll.filter((t) => taskSelectors.canViewTask(user, t));
  const completed = tasks.filter(t => t.status === "Completed");

  if (selectedTask) {
    return <TaskInlineDetail task={selectedTask} onBack={() => setSelectedTask(null)} onTaskUpdate={setSelectedTask} />;
  }

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2">
          <CheckCircle2 className="h-5 w-5 text-green-600" />Completed Tasks
        </h1>
        <p className="text-muted-foreground text-sm">{completed.length} tasks completed</p>
      </div>

      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Module</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Assigned To</TableHead>
              <TableHead>Due Date</TableHead>
              <TableHead>Completed At</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {completed.map(t => {
              const linked = `${t.linkedModule} · ${t.linkedId}`;
              return (
                <TableRow key={t.taskId} className="cursor-pointer opacity-80 hover:opacity-100" onClick={() => setSelectedTask(t)}>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      {t.isAutoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                      <div>
                        <p className="text-sm font-medium">{t.title}</p>
                        {linked && <p className="text-xs text-muted-foreground flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{linked}</p>}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className="text-[10px]">{t.linkedModule}</Badge></TableCell>
                  <TableCell><Badge variant="outline" className="text-[10px]">{t.type}</Badge></TableCell>
                  <TableCell>
                    <p className="text-sm">{t.assignedTo}</p>
                    <p className="text-[10px] text-muted-foreground">by {t.assignedBy}</p>
                  </TableCell>
                  <TableCell className="text-sm">{t.dueDate}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{t.completedAt ?? "—"}</TableCell>
                </TableRow>
              );
            })}
            {completed.length === 0 && <TableRow><TableCell colSpan={6} className="text-center py-8 text-muted-foreground">No completed tasks</TableCell></TableRow>}
          </TableBody>
        </Table>
      </div>


    </motion.div>
  );
};

export default CompletedTasks;
