import { useState } from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Zap, Link2 } from "lucide-react";
import TaskInlineDetail from "@/components/tasks/TaskInlineDetail";
import type { Task } from "@/modules/tasks/types";
import { taskSelectors, useCurrentUser, useTasks } from "@/modules/tasks/hooks";
import { isSameDay, parseISO } from "date-fns";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Pending: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Blocked: "bg-red-50 text-red-700 border-red-200", Completed: "bg-green-50 text-green-700 border-green-200", Cancelled: "bg-muted text-muted-foreground" };

const MyTasks = () => {
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const user = useCurrentUser();
  const tasksAll = useTasks();
  const tasks = tasksAll.filter((t) => taskSelectors.canViewTask(user, t));
  const myTasks = tasks.filter(t => t.assignedTo === user.displayName && t.status !== "Completed" && t.status !== "Cancelled");
  const completedToday = tasks.filter(t => t.assignedTo === user.displayName && t.status === "Completed" && t.completedAt && isSameDay(parseISO(t.completedAt), new Date()));

  if (selectedTask) {
    return <TaskInlineDetail task={selectedTask} onBack={() => setSelectedTask(null)} onTaskUpdate={setSelectedTask} />;
  }

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">My Tasks</h1>
        <p className="text-muted-foreground text-sm">Tasks assigned to {user.displayName} — {myTasks.length} active, {completedToday.length} completed today</p>
      </div>

      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Module</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Due Date</TableHead>
              <TableHead>Priority</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {myTasks.map(t => {
              const linked = `${t.linkedModule} · ${t.linkedId}`;
              const overdue = taskSelectors.isTaskOverdue(t, new Date());
              return (
                <TableRow key={t.taskId} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      {t.isAutoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                      <div>
                        <p className="text-sm font-medium">{t.title}</p>
                        {linked && <p className="text-xs text-muted-foreground flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{linked}</p>}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className="text-[10px]">{t.linkedModule}</Badge></TableCell>
                  <TableCell className="text-sm">{t.type}</TableCell>
                  <TableCell className={`text-sm ${overdue ? "text-destructive font-medium" : ""}`}>{t.dueDate}</TableCell>
                  <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                  <TableCell><Badge variant="outline" className={`text-[10px] ${statusColor[t.status]}`}>{t.status}</Badge></TableCell>
                </TableRow>
              );
            })}
            {myTasks.length === 0 && <TableRow><TableCell colSpan={6} className="text-center py-8 text-muted-foreground">No active tasks assigned to you</TableCell></TableRow>}
          </TableBody>
        </Table>
      </div>

      {completedToday.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-muted-foreground mb-2">Completed Today</h2>
          <div className="border rounded-lg">
            <Table>
              <TableHeader>
                <TableRow><TableHead>Title</TableHead><TableHead>Module</TableHead><TableHead>Completed At</TableHead></TableRow>
              </TableHeader>
              <TableBody>
                {completedToday.map(t => (
                  <TableRow key={t.taskId} className="cursor-pointer opacity-70" onClick={() => setSelectedTask(t)}>
                    <TableCell className="text-sm">{t.title}</TableCell>
                    <TableCell><Badge variant="outline" className="text-[10px]">{t.linkedModule}</Badge></TableCell>
                    <TableCell className="text-sm">{t.completedAt ?? "—"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      )}


    </motion.div>
  );
};

export default MyTasks;
