import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Clock, AlertTriangle, CheckCircle2, Zap, MapPin, Calendar, ClipboardList } from "lucide-react";
import TaskDetailModal from "@/components/tasks/TaskDetailModal";
import type { Task } from "@/modules/tasks/types";
import { taskActions, taskSelectors, useCurrentUser, useTasks } from "@/modules/tasks/hooks";
import { isSameDay, parseISO } from "date-fns";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Pending: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Blocked: "bg-red-50 text-red-700 border-red-200", Completed: "bg-green-50 text-green-700 border-green-200", Cancelled: "bg-muted text-muted-foreground" };

const TaskDashboard = () => {
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const tasksAll = useTasks();
  const user = useCurrentUser();
  const tasks = tasksAll.filter((t) => taskSelectors.canViewTask(user, t));
  const today = new Date();

  const totalPending = tasks.filter((t) => t.status === "Pending").length;
  const highPriority = tasks.filter((t) => (t.priority === "High" || t.priority === "Critical") && t.status !== "Completed" && t.status !== "Cancelled").length;
  const dueTodayTasks = tasks.filter((t) => taskSelectors.isDueToday(t, today));
  const overdueTasks = tasks.filter((t) => taskSelectors.isTaskOverdue(t, today));
  const completedToday = tasks.filter((t) => t.status === "Completed" && t.completedAt && isSameDay(parseISO(t.completedAt), today));
  const autoCount = tasks.filter((t) => t.isAutoGenerated).length;

  // Module-wise breakdown
  const moduleMap = tasks.reduce((acc, t) => {
    if (!acc[t.linkedModule]) acc[t.linkedModule] = { total: 0, overdue: 0 };
    acc[t.linkedModule].total++;
    if (taskSelectors.isTaskOverdue(t, today)) acc[t.linkedModule].overdue++;
    return acc;
  }, {} as Record<string, { total: number; overdue: number }>);

  const kpis = [
    { label: "Total Pending", value: totalPending, icon: ClipboardList, color: "text-primary", bg: "bg-primary/5" },
    { label: "High Priority", value: highPriority, icon: AlertTriangle, color: "text-orange-600", bg: "bg-orange-50" },
    { label: "Due Today", value: dueTodayTasks.length, icon: Clock, color: "text-blue-600", bg: "bg-blue-50" },
    { label: "Overdue", value: overdueTasks.length, icon: AlertTriangle, color: "text-destructive", bg: "bg-red-50" },
    { label: "Auto-Generated", value: autoCount, icon: Zap, color: "text-purple-600", bg: "bg-purple-50" },
    { label: "Completed Today", value: completedToday.length, icon: CheckCircle2, color: "text-green-600", bg: "bg-green-50" },
  ];

  useEffect(() => {
    if (user.role !== "Admin") return;
    const criticalOverdue = overdueTasks.filter((t) => t.priority === "Critical");
    if (criticalOverdue.length === 0) return;
    toast({
      title: "Escalation: Critical tasks overdue",
      description: `${criticalOverdue.length} critical task(s) are overdue. Please review and act.`,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user.role]);

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Task Dashboard</h1>
          <p className="text-muted-foreground text-sm">Central operational engine: Manual, Auto-generated, and Scheduled recurring tasks</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">Role</span>
          <Select value={user.role} onValueChange={(v) => taskActions.setCurrentUserRole(v as any)}>
            <SelectTrigger className="w-44 h-9 bg-background">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="bg-popover">
              <SelectItem value="Admin">Admin</SelectItem>
              <SelectItem value="Finance">Finance</SelectItem>
              <SelectItem value="Store Manager">Store Manager</SelectItem>
              <SelectItem value="Event Manager">Event Manager</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-6 gap-4">
        {kpis.map((kpi, i) => (
          <Card key={i} className="hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${kpi.bg} mb-2`}>
                <kpi.icon className={`h-5 w-5 ${kpi.color}`} />
              </div>
              <p className="text-2xl font-bold">{kpi.value}</p>
              <p className="text-[11px] text-muted-foreground">{kpi.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Due Today */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Clock className="h-4 w-4 text-blue-600" />Tasks Due Today
              <Badge variant="secondary" className="text-xs">{dueTodayTasks.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Task</TableHead><TableHead>Assignee</TableHead><TableHead>Priority</TableHead><TableHead>Status</TableHead></TableRow></TableHeader>
              <TableBody>
                {dueTodayTasks.slice(0, 6).map(t => (
                  <TableRow key={t.taskId} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                    <TableCell>
                      <div className="flex items-center gap-1.5">
                        {t.isAutoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                        <div>
                          <p className="text-sm font-medium">{t.title}</p>
                          <p className="text-xs text-muted-foreground">{t.linkedModule}</p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell className="text-sm">{t.assignedTo}</TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${statusColor[t.status]}`}>{t.status}</Badge></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Overdue */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <AlertTriangle className="h-4 w-4 text-destructive" />Overdue Tasks
              <Badge variant="destructive" className="text-xs">{overdueTasks.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Task</TableHead><TableHead>Due</TableHead><TableHead>Assignee</TableHead><TableHead>Priority</TableHead></TableRow></TableHeader>
              <TableBody>
                {overdueTasks.map(t => (
                  <TableRow key={t.taskId} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                    <TableCell>
                      <p className="text-sm font-medium">{t.title}</p>
                      <p className="text-xs text-muted-foreground">{t.linkedModule}</p>
                    </TableCell>
                    <TableCell className="text-sm text-destructive font-medium">{t.dueDate}</TableCell>
                    <TableCell className="text-sm">{t.assignedTo}</TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                  </TableRow>
                ))}
                {overdueTasks.length === 0 && <TableRow><TableCell colSpan={4} className="text-center py-6 text-muted-foreground">No overdue tasks</TableCell></TableRow>}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Module breakdown */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" />Module-wise Breakdown</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Module</TableHead><TableHead className="text-center">Total</TableHead><TableHead className="text-center">Overdue</TableHead></TableRow></TableHeader>
              <TableBody>
                {Object.entries(moduleMap).sort((a, b) => b[1].total - a[1].total).map(([name, data]) => (
                  <TableRow key={name}>
                    <TableCell className="font-medium text-sm">{name}</TableCell>
                    <TableCell className="text-center text-sm">{data.total}</TableCell>
                    <TableCell className="text-center">{data.overdue > 0 ? <Badge variant="destructive" className="text-xs">{data.overdue}</Badge> : <span className="text-xs text-muted-foreground">0</span>}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Completed today */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2"><Calendar className="h-4 w-4 text-primary" />Completed Today</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Task</TableHead><TableHead>Module</TableHead><TableHead>Assignee</TableHead><TableHead>Completed At</TableHead></TableRow></TableHeader>
              <TableBody>
                {completedToday.slice(0, 8).map((t) => (
                  <TableRow key={t.taskId} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                    <TableCell className="font-medium text-sm">{t.title}</TableCell>
                    <TableCell><Badge variant="outline" className="text-[10px]">{t.linkedModule}</Badge></TableCell>
                    <TableCell className="text-sm">{t.assignedTo}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">{t.completedAt ?? "—"}</TableCell>
                  </TableRow>
                ))}
                {completedToday.length === 0 && <TableRow><TableCell colSpan={4} className="text-center py-6 text-muted-foreground">No tasks completed today</TableCell></TableRow>}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      <TaskDetailModal task={selectedTask} open={!!selectedTask} onOpenChange={() => setSelectedTask(null)} />
    </motion.div>
  );
};

export default TaskDashboard;
