import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Calendar, Link2, User, Zap } from "lucide-react";
import type { Task, TaskStatus } from "@/modules/tasks/types";
import { taskActions, taskSelectors, useCurrentUser } from "@/modules/tasks/hooks";

const priorityColor: Record<string, string> = {
  Critical: "bg-red-50 text-red-700 border-red-200",
  High: "bg-orange-50 text-orange-700 border-orange-200",
  Medium: "bg-amber-50 text-amber-700 border-amber-200",
  Low: "bg-green-50 text-green-700 border-green-200",
};

const statusColor: Record<string, string> = {
  Pending: "bg-blue-50 text-blue-700 border-blue-200",
  "In Progress": "bg-amber-50 text-amber-700 border-amber-200",
  Blocked: "bg-red-50 text-red-700 border-red-200",
  Completed: "bg-green-50 text-green-700 border-green-200",
  Cancelled: "bg-muted text-muted-foreground",
};

interface TaskDetailModalProps {
  task: Task | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const TaskDetailModal = ({ task, open, onOpenChange }: TaskDetailModalProps) => {
  if (!task) return null;
  const navigate = useNavigate();
  const user = useCurrentUser();
  const [nextStatus, setNextStatus] = useState<TaskStatus>(task.status);

  const viewSourcePath = useMemo(() => taskSelectors.getViewSourcePath(task), [task]);
  const overdue = taskSelectors.isTaskOverdue(task, new Date());
  const canUpdate =
    user.role === "Admin" ||
    task.assignedTo === user.displayName ||
    taskSelectors.canCompleteTask(user, task);
  const canMarkCompleted =
    user.role === "Admin" ||
    taskSelectors.canCompleteTask(user, task) ||
    (task.type === "Manual" && task.assignedTo === user.displayName);
  const statusOptions: TaskStatus[] = ["Pending", "In Progress", "Blocked", "Completed", "Cancelled"];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs font-mono text-muted-foreground">{task.taskId}</span>
            <Badge variant="outline" className={`text-[10px] ${statusColor[task.status]}`}>{task.status}</Badge>
            <Badge variant="outline" className={`text-[10px] ${priorityColor[task.priority]}`}>{task.priority}</Badge>
            {task.isAutoGenerated && (
              <Badge variant="outline" className="text-[10px] bg-purple-50 text-purple-700 border-purple-200 gap-0.5">
                <Zap className="h-2.5 w-2.5" />
                Auto
              </Badge>
            )}
            {overdue && (
              <Badge variant="destructive" className="text-[10px]">Overdue</Badge>
            )}
          </div>
          <DialogTitle className="text-lg mt-1">{task.title}</DialogTitle>
        </DialogHeader>

        {task.description && (
          <div className="mt-2 p-3 bg-muted/50 rounded-lg border text-sm">
            {task.description}
          </div>
        )}

        <div className="mt-4 grid grid-cols-2 gap-4">
          <div className="space-y-3">
            <div>
              <p className="text-[10px] uppercase text-muted-foreground font-medium">Assigned To</p>
              <div className="flex items-center gap-1.5 text-sm mt-0.5">
                <User className="h-3.5 w-3.5 text-muted-foreground" />
                <span className="font-medium">{task.assignedTo}</span>
              </div>
            </div>
            <div>
              <p className="text-[10px] uppercase text-muted-foreground font-medium">Assigned By</p>
              <p className="text-sm font-medium">{task.assignedBy}</p>
            </div>
            <div>
              <p className="text-[10px] uppercase text-muted-foreground font-medium">Type</p>
              <Badge variant="outline" className="text-xs">{task.type}</Badge>
            </div>
          </div>
          <div className="space-y-3">
            <div>
              <p className="text-[10px] uppercase text-muted-foreground font-medium">Due Date</p>
              <div className="flex items-center gap-1.5 text-sm mt-0.5">
                <Calendar className="h-3.5 w-3.5 text-muted-foreground" />
                <span className={overdue ? "text-destructive font-medium" : ""}>{task.dueDate}</span>
              </div>
            </div>
            <div>
              <p className="text-[10px] uppercase text-muted-foreground font-medium">Linked</p>
              <div className="flex items-center gap-2 flex-wrap mt-0.5">
                <Badge variant="outline" className="text-xs">{task.linkedModule}</Badge>
                <span className="text-xs font-mono text-muted-foreground">{task.linkedId}</span>
              </div>
              {viewSourcePath && (
                <Button
                  variant="link"
                  className="px-0 h-auto text-xs"
                  onClick={() => {
                    onOpenChange(false);
                    navigate(viewSourcePath);
                  }}
                >
                  <Link2 className="h-3.5 w-3.5 mr-1" />
                  View Source
                </Button>
              )}
            </div>
          </div>
        </div>

        <Separator className="my-4" />

        <div className="space-y-2">
          <p className="text-[10px] uppercase text-muted-foreground font-medium">Update Status</p>
          <div className="flex items-center gap-2">
            <Select value={nextStatus} onValueChange={(v) => setNextStatus(v as TaskStatus)} disabled={!canUpdate}>
              <SelectTrigger className="w-56 bg-background">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-popover">
                {statusOptions.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button
              onClick={() => taskActions.updateTaskStatus(task.taskId, nextStatus)}
              disabled={
                !canUpdate ||
                nextStatus === task.status ||
                (nextStatus === "Completed" && !canMarkCompleted)
              }
            >
              Save
            </Button>
            {!canUpdate && (
              <span className="text-xs text-muted-foreground">
                You don’t have permission to complete/update this task.
              </span>
            )}
            {canUpdate && nextStatus === "Completed" && !canMarkCompleted && (
              <span className="text-xs text-muted-foreground">
                You don’t have permission to mark this task Completed.
              </span>
            )}
          </div>
        </div>

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default TaskDetailModal;
