import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowLeft, Edit, Zap, Link2 } from "lucide-react";
import { motion } from "framer-motion";
import type { Task } from "@/modules/tasks/types";
import { taskActions, taskSelectors } from "@/modules/tasks/hooks";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Pending: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Blocked: "bg-red-50 text-red-700 border-red-200", Completed: "bg-green-50 text-green-700 border-green-200", Cancelled: "bg-muted text-muted-foreground" };

interface TaskInlineDetailProps {
    task: Task;
    onBack: () => void;
    onTaskUpdate?: (task: Task) => void;
}

const TaskInlineDetail = ({ task: t, onBack, onTaskUpdate }: TaskInlineDetailProps) => {
    const overdue = taskSelectors.isTaskOverdue(t, new Date());
    const linked = `${t.linkedModule} · ${t.linkedId}`;

    const handleStatusChange = () => {
        const newStatus = t.status === "Completed" ? "Pending" : "Completed";
        taskActions.updateTaskStatus(t.taskId, newStatus);
        if (onTaskUpdate) {
            onTaskUpdate({ ...t, status: newStatus });
        }
    };

    return (
        <div className="p-6 space-y-6">
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
                {/* Header */}
                <div className="flex items-start justify-between mb-6">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" onClick={onBack}>
                            <ArrowLeft className="h-4 w-4" />
                        </Button>
                        <div>
                            <div className="flex items-center gap-3">
                                <h1 className="text-2xl font-semibold tracking-tight">{t.taskId}</h1>
                                <Badge variant="outline" className={statusColor[t.status]}>{t.status}</Badge>
                                {t.isAutoGenerated && <Badge variant="secondary" className="gap-1"><Zap className="h-3 w-3" />Auto-generated</Badge>}
                            </div>
                            <p className="text-muted-foreground text-sm mt-1">{t.title}</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" size="sm" className="gap-2"><Edit className="h-4 w-4" />Edit</Button>
                        <Button variant="outline" size="sm" onClick={handleStatusChange}>
                            {t.status === "Completed" ? "Reopen" : "Mark Complete"}
                        </Button>
                    </div>
                </div>

                {/* Tabs */}
                <Tabs defaultValue="details" className="space-y-4">
                    <div className="border-b border-border">
                        <TabsList className="w-full justify-start border-b-0 rounded-none h-auto p-0 bg-transparent gap-0">
                            <TabsTrigger value="details" className="rounded-none border-b-2 border-transparent data-[state=active]:border-amber-700 data-[state=active]:bg-transparent data-[state=active]:text-foreground data-[state=active]:font-medium px-4 py-2 text-sm text-muted-foreground">
                                Task Details
                            </TabsTrigger>
                            <TabsTrigger value="linked" className="rounded-none border-b-2 border-transparent data-[state=active]:border-amber-700 data-[state=active]:bg-transparent data-[state=active]:text-foreground data-[state=active]:font-medium px-4 py-2 text-sm text-muted-foreground">
                                Linked Module Info
                            </TabsTrigger>
                        </TabsList>
                    </div>

                    <TabsContent value="details" className="space-y-6">
                        <div>
                            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Basic Information</h3>
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-y-3 gap-x-8 text-sm">
                                <div><span className="text-muted-foreground">Task ID:</span> <span className="ml-2 font-medium font-mono text-xs">{t.taskId}</span></div>
                                <div><span className="text-muted-foreground">Type:</span> <span className="ml-2"><Badge variant="outline" className="text-xs">{t.type}</Badge></span></div>
                                <div><span className="text-muted-foreground">Priority:</span> <span className="ml-2"><Badge variant="outline" className={`text-xs ${priorityColor[t.priority]}`}>{t.priority}</Badge></span></div>
                                <div><span className="text-muted-foreground">Status:</span> <span className="ml-2"><Badge variant="outline" className={`text-xs ${statusColor[t.status]}`}>{t.status}</Badge></span></div>
                                <div><span className="text-muted-foreground">Due Date:</span> <span className={`ml-2 font-medium ${overdue ? 'text-destructive' : ''}`}>{t.dueDate}</span></div>
                                <div><span className="text-muted-foreground">Auto-generated:</span> <span className="ml-2">{t.isAutoGenerated ? "Yes" : "No"}</span></div>
                            </div>
                        </div>
                        <hr className="border-border" />
                        <div>
                            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Assignment</h3>
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-y-3 gap-x-8 text-sm">
                                <div><span className="text-muted-foreground">Assigned To:</span> <span className="ml-2 font-medium">{t.assignedTo}</span></div>
                                <div><span className="text-muted-foreground">Assigned By:</span> <span className="ml-2 font-medium">{t.assignedBy}</span></div>
                            </div>
                        </div>
                        <hr className="border-border" />
                        <div>
                            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Description</h3>
                            <p className="text-sm text-muted-foreground">{t.description || "No description provided."}</p>
                        </div>
                    </TabsContent>

                    <TabsContent value="linked" className="space-y-6">
                        <div>
                            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3">Linked Module Information</h3>
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-y-3 gap-x-8 text-sm">
                                <div><span className="text-muted-foreground">Module:</span> <span className="ml-2"><Badge variant="outline" className="text-xs">{t.linkedModule}</Badge></span></div>
                                <div><span className="text-muted-foreground">Linked ID:</span> <span className="ml-2 font-medium font-mono text-xs flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{t.linkedId}</span></div>
                            </div>
                            <div className="mt-4">
                                <p className="text-xs text-muted-foreground">This task is linked to: {linked}</p>
                            </div>
                        </div>
                    </TabsContent>
                </Tabs>
            </motion.div>
        </div>
    );
};

export default TaskInlineDetail;
