// ==========================================
// TASK MANAGEMENT MODULE - DATA LAYER
// Linked operational task system
// ==========================================

import { templeStructures, eventRefs, freelancerRefs } from "./templeData";

export { templeStructures, eventRefs, freelancerRefs };

// ---- TASK ENTITY ----
export type TaskPriority = "Low" | "Medium" | "High" | "Critical";
export type TaskStatus = "Open" | "In Progress" | "Completed" | "Overdue" | "Cancelled";
export type AssigneeType = "Employee" | "Freelancer" | "Volunteer" | "Team" | "Role";
export type SourceModule = "Event" | "Seva" | "Darshan" | "Kitchen" | "Inventory" | "Maintenance" | "Freelancer" | "Manual";

export interface TaskActivity {
  timestamp: string;
  action: string;
  by: string;
  notes?: string;
}

export interface TaskAttachment {
  name: string;
  type: "photo" | "video" | "document";
  timestamp: string;
  uploadedBy: string;
}

export interface TempleTask {
  id: string;
  title: string;
  description: string;
  templeId: string;
  structureId: string;
  structureName: string;
  priority: TaskPriority;
  status: TaskStatus;
  startDate: string;
  dueDate: string;
  // Assignment
  assignedTo: string;
  assigneeType: AssigneeType;
  createdBy: string;
  // Mandatory linking (at least one)
  sourceModule: SourceModule;
  eventId?: string;
  eventName?: string;
  sevaId?: string;
  sevaName?: string;
  darshanSlotId?: string;
  stockTransactionId?: string;
  kitchenBatchId?: string;
  maintenanceRequestId?: string;
  freelancerId?: string;
  freelancerName?: string;
  // Auto-generation
  autoGenerated: boolean;
  // Activity & attachments
  activities: TaskActivity[];
  attachments: TaskAttachment[];
  // Cancellation
  cancelReason?: string;
}

export const templeTasks: TempleTask[] = [
  // ======= EVENT-GENERATED TASKS (Maha Shivaratri) =======
  {
    id: "TSK-001", title: "Decorate Main Temple – Maha Shivaratri", description: "Full mandap & entrance decoration with flowers and lighting for Maha Shivaratri",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Open", startDate: "2026-02-14", dueDate: "2026-02-14",
    assignedTo: "Decor Dreams", assigneeType: "Freelancer", createdBy: "System",
    sourceModule: "Event", eventId: "EVT-004", eventName: "Maha Shivaratri", freelancerId: "FRL-0002", freelancerName: "Decor Dreams",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Generated from Event EVT-004 freelancer assignment" }],
    attachments: [],
  },
  {
    id: "TSK-002", title: "Setup Sound System – Maha Shivaratri", description: "Full PA system setup for main hall + live stream configuration",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Open", startDate: "2026-02-15", dueDate: "2026-02-15",
    assignedTo: "Sound Waves Pro", assigneeType: "Freelancer", createdBy: "System",
    sourceModule: "Event", eventId: "EVT-004", eventName: "Maha Shivaratri", freelancerId: "FRL-0003", freelancerName: "Sound Waves Pro",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "PA system + live streaming for Maha Shivaratri" }],
    attachments: [],
  },
  {
    id: "TSK-003", title: "Event Photography Setup – Maha Shivaratri", description: "Setup cameras at Main Temple by 4 AM for multi-angle coverage",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Open", startDate: "2026-02-15", dueDate: "2026-02-15",
    assignedTo: "Pixel Studio", assigneeType: "Freelancer", createdBy: "System",
    sourceModule: "Event", eventId: "EVT-004", eventName: "Maha Shivaratri", freelancerId: "FRL-0001", freelancerName: "Pixel Studio",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System" }],
    attachments: [],
  },
  {
    id: "TSK-004", title: "Festival Lighting Setup – Maha Shivaratri", description: "LED & traditional lighting installation for festival",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Open", startDate: "2026-02-14", dueDate: "2026-02-14",
    assignedTo: "Heritage Electricals", assigneeType: "Freelancer", createdBy: "System",
    sourceModule: "Event", eventId: "EVT-004", eventName: "Maha Shivaratri", freelancerId: "FRL-0007", freelancerName: "Heritage Electricals",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System" }],
    attachments: [],
  },
  {
    id: "TSK-005", title: "Crowd Control Deployment – Maha Shivaratri", description: "120 volunteers at Main Gate + Queue Lines, 6 AM – 2 PM shift",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "Critical", status: "Open", startDate: "2026-02-15", dueDate: "2026-02-15",
    assignedTo: "Crowd Control Team (120)", assigneeType: "Volunteer", createdBy: "System",
    sourceModule: "Event", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Volunteer crowd management" }],
    attachments: [],
  },
  // ======= KITCHEN-GENERATED TASKS =======
  {
    id: "TSK-006", title: "Morning Laddu Production – 5000 units", description: "Batch BTH-2026-0891: Auto-deduct 125kg Besan, 100kg Sugar, 60L Ghee, 10kg Cashew",
    templeId: "TMP-001", structureId: "STR-007", structureName: "Kitchen", priority: "High", status: "In Progress", startDate: "2026-02-10", dueDate: "2026-02-10",
    assignedTo: "Team A", assigneeType: "Team", createdBy: "System",
    sourceModule: "Kitchen", kitchenBatchId: "BTH-2026-0891",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-10 05:00", action: "Task auto-created", by: "System", notes: "Kitchen batch scheduled" },
      { timestamp: "2026-02-10 06:00", action: "Status → In Progress", by: "Head Cook – Team A" },
    ],
    attachments: [],
  },
  {
    id: "TSK-007", title: "Annadanam Preparation – 10,000 Meals", description: "Linked to EVT-004 Maha Shivaratri. 500kg Rice, 150kg Dal, 50L Ghee, 80L Sesame Oil",
    templeId: "TMP-001", structureId: "STR-005", structureName: "Annadanam Hall", priority: "Critical", status: "Open", startDate: "2026-02-15", dueDate: "2026-02-15",
    assignedTo: "Team C", assigneeType: "Team", createdBy: "System",
    sourceModule: "Kitchen", kitchenBatchId: "BTH-2026-0888", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Annadanam linked to Maha Shivaratri" }],
    attachments: [],
  },
  // ======= INVENTORY-GENERATED TASKS =======
  {
    id: "TSK-008", title: "Procure Ghee – 200L Shortage for Shivaratri", description: "Current: 45L, Required: 200L. Create PO for Nandi Oil & Ghee immediately.",
    templeId: "TMP-001", structureId: "STR-007", structureName: "Kitchen", priority: "Critical", status: "Open", startDate: "2026-02-10", dueDate: "2026-02-13",
    assignedTo: "Store Manager", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Inventory", stockTransactionId: "REQ-002", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Stock shortage detected from event allocation" }],
    attachments: [],
  },
  {
    id: "TSK-009", title: "Procure Flower Arrangements – 12 pcs Shortage", description: "Current: 3, Required: 15. Contact Devi Decorations for festival order.",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Open", startDate: "2026-02-10", dueDate: "2026-02-13",
    assignedTo: "Store Manager", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Inventory", stockTransactionId: "REQ-003", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System" }],
    attachments: [],
  },
  {
    id: "TSK-010", title: "Verify Brass Lamp Transfer to Padmavathi Shrine", description: "2 brass lamps transferred from Main Temple. Verify condition and placement.",
    templeId: "TMP-001", structureId: "STR-002", structureName: "Padmavathi Shrine", priority: "Medium", status: "Completed", startDate: "2026-02-09", dueDate: "2026-02-09",
    assignedTo: "Temple Attendant", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Inventory", stockTransactionId: "TXN-009",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-09 09:30", action: "Task auto-created", by: "System", notes: "Stock transfer verification" },
      { timestamp: "2026-02-09 10:15", action: "Status → Completed", by: "Temple Attendant", notes: "Both lamps in good condition and placed at altar" },
    ],
    attachments: [{ name: "lamp_placement.jpg", type: "photo", timestamp: "2026-02-09 10:10", uploadedBy: "Temple Attendant" }],
  },
  // ======= SEVA-GENERATED TASKS =======
  {
    id: "TSK-011", title: "Morning Abhishekam Material Setup", description: "Prepare: 5L Milk, 1kg Rose Petals, 0.2kg Camphor, 10 Coconut, 10 Jasmine Garlands",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "In Progress", startDate: "2026-02-10", dueDate: "2026-02-10",
    assignedTo: "Pandit Sharma", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Seva", sevaId: "Abhishekam", sevaName: "Morning Abhishekam – Main Temple",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-10 04:30", action: "Task auto-created", by: "System", notes: "Daily seva material prep" },
      { timestamp: "2026-02-10 05:00", action: "Status → In Progress", by: "Pandit Sharma" },
    ],
    attachments: [],
  },
  {
    id: "TSK-012", title: "Suprabhatam Ritual Preparation", description: "Rose petals, jasmine garlands, camphor, and incense for morning Suprabhatam",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "High", status: "Completed", startDate: "2026-02-10", dueDate: "2026-02-10",
    assignedTo: "Pandit Sharma", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Seva", sevaId: "Suprabhatam", sevaName: "Suprabhatam – Main Temple",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-10 04:00", action: "Task auto-created", by: "System" },
      { timestamp: "2026-02-10 04:30", action: "Status → In Progress", by: "Pandit Sharma" },
      { timestamp: "2026-02-10 05:30", action: "Status → Completed", by: "Pandit Sharma", notes: "All materials arranged at sanctum" },
    ],
    attachments: [{ name: "suprabhatam_setup.jpg", type: "photo", timestamp: "2026-02-10 05:25", uploadedBy: "Pandit Sharma" }],
  },
  // ======= DARSHAN-GENERATED TASKS =======
  {
    id: "TSK-013", title: "Morning Darshan Queue Setup", description: "Setup garlands, camphor, and incense at darshan counters for 20 slots",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "Medium", status: "Completed", startDate: "2026-02-10", dueDate: "2026-02-10",
    assignedTo: "Temple Attendant", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Darshan", darshanSlotId: "DS-2026-02-10-AM",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-10 05:00", action: "Task auto-created", by: "System" },
      { timestamp: "2026-02-10 05:45", action: "Status → Completed", by: "Temple Attendant" },
    ],
    attachments: [],
  },
  // ======= MAINTENANCE-GENERATED TASKS =======
  {
    id: "TSK-014", title: "Generator Maintenance Check", description: "Quarterly maintenance check – spare parts awaited from supplier",
    templeId: "TMP-001", structureId: "STR-008", structureName: "Administration", priority: "High", status: "Overdue", startDate: "2026-02-05", dueDate: "2026-02-07",
    assignedTo: "Electrical Team", assigneeType: "Team", createdBy: "System",
    sourceModule: "Maintenance", maintenanceRequestId: "MNT-001",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-05 08:00", action: "Task auto-created", by: "System", notes: "Scheduled maintenance" },
      { timestamp: "2026-02-07 18:00", action: "Status → Overdue", by: "System", notes: "Due date crossed – spare parts not received" },
    ],
    attachments: [],
  },
  {
    id: "TSK-015", title: "Fire Extinguisher Inspection", description: "Quarterly inspection overdue – all buildings",
    templeId: "TMP-001", structureId: "STR-008", structureName: "Administration", priority: "Critical", status: "Overdue", startDate: "2026-02-04", dueDate: "2026-02-06",
    assignedTo: "Safety Officer", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Maintenance", maintenanceRequestId: "MNT-002",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-04 08:00", action: "Task auto-created", by: "System" },
      { timestamp: "2026-02-06 18:00", action: "Status → Overdue", by: "System" },
    ],
    attachments: [],
  },
  // ======= MANUAL TASKS =======
  {
    id: "TSK-016", title: "Coordinate with Police for Shivaratri Security", description: "Confirm deployment plan with SP Office for Maha Shivaratri crowd management",
    templeId: "TMP-001", structureId: "STR-008", structureName: "Administration", priority: "High", status: "In Progress", startDate: "2026-02-08", dueDate: "2026-02-13",
    assignedTo: "Temple Admin", assigneeType: "Employee", createdBy: "Temple Admin",
    sourceModule: "Manual", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: false,
    activities: [
      { timestamp: "2026-02-08 10:00", action: "Task created", by: "Temple Admin" },
      { timestamp: "2026-02-09 14:00", action: "Status → In Progress", by: "Temple Admin", notes: "Meeting scheduled with SP office on Feb 12" },
    ],
    attachments: [],
  },
  {
    id: "TSK-017", title: "VIP Lounge Preparation – Governor Visit", description: "Prepare VIP lounge with seating, refreshments, and protocol arrangements",
    templeId: "TMP-001", structureId: "STR-006", structureName: "Cultural Hall", priority: "High", status: "Open", startDate: "2026-02-10", dueDate: "2026-02-14",
    assignedTo: "Admin Team", assigneeType: "Team", createdBy: "Temple Admin",
    sourceModule: "Manual",
    autoGenerated: false,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task created", by: "Temple Admin" }],
    attachments: [],
  },
  {
    id: "TSK-018", title: "Water Tank Cleaning – All Buildings", description: "Quarterly water tank cleaning and quality test across all structures",
    templeId: "TMP-001", structureId: "STR-008", structureName: "Administration", priority: "Medium", status: "Overdue", startDate: "2026-02-03", dueDate: "2026-02-05",
    assignedTo: "Maintenance Crew", assigneeType: "Team", createdBy: "Temple Admin",
    sourceModule: "Maintenance", maintenanceRequestId: "MNT-003",
    autoGenerated: false,
    activities: [
      { timestamp: "2026-02-03 08:00", action: "Task created", by: "Temple Admin" },
      { timestamp: "2026-02-05 18:00", action: "Status → Overdue", by: "System" },
    ],
    attachments: [],
  },
  {
    id: "TSK-019", title: "CCTV Storage Review", description: "Review CCTV storage capacity and archive old footage",
    templeId: "TMP-001", structureId: "STR-008", structureName: "Administration", priority: "Low", status: "Overdue", startDate: "2026-02-02", dueDate: "2026-02-04",
    assignedTo: "IT Admin", assigneeType: "Employee", createdBy: "Temple Admin",
    sourceModule: "Maintenance", maintenanceRequestId: "MNT-004",
    autoGenerated: false,
    activities: [{ timestamp: "2026-02-02 10:00", action: "Task created", by: "Temple Admin" }],
    attachments: [],
  },
  {
    id: "TSK-020", title: "Prasadam Counter Restock – Afternoon", description: "Restock laddu and pulihora counters for afternoon devotees",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "Medium", status: "Completed", startDate: "2026-02-09", dueDate: "2026-02-09",
    assignedTo: "Counter Staff", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Kitchen", kitchenBatchId: "BTH-2026-0890",
    autoGenerated: true,
    activities: [
      { timestamp: "2026-02-09 12:00", action: "Task auto-created", by: "System" },
      { timestamp: "2026-02-09 13:30", action: "Status → Completed", by: "Counter Staff" },
    ],
    attachments: [{ name: "counter_restocked.jpg", type: "photo", timestamp: "2026-02-09 13:25", uploadedBy: "Counter Staff" }],
  },
  // ======= FREELANCER SETUP TASKS =======
  {
    id: "TSK-021", title: "Decor Dreams – Material Handover Verification", description: "Verify materials issued to Decor Dreams for Maha Shivaratri decoration",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "Medium", status: "Open", startDate: "2026-02-14", dueDate: "2026-02-14",
    assignedTo: "Store Keeper", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Freelancer", freelancerId: "FRL-0002", freelancerName: "Decor Dreams", stockTransactionId: "REQ-005",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Material handover for freelancer assignment" }],
    attachments: [],
  },
  {
    id: "TSK-022", title: "Sound Equipment Return Check – Post Shivaratri", description: "Verify return of all PA equipment from Sound Waves Pro after event",
    templeId: "TMP-001", structureId: "STR-001", structureName: "Main Temple", priority: "Medium", status: "Open", startDate: "2026-02-16", dueDate: "2026-02-16",
    assignedTo: "Store Keeper", assigneeType: "Employee", createdBy: "System",
    sourceModule: "Freelancer", freelancerId: "FRL-0003", freelancerName: "Sound Waves Pro", eventId: "EVT-004", eventName: "Maha Shivaratri",
    autoGenerated: true,
    activities: [{ timestamp: "2026-02-10 09:00", action: "Task auto-created", by: "System", notes: "Post-event equipment return" }],
    attachments: [],
  },
];

// ---- DROPDOWN OPTIONS ----
export const taskCategories = ["Ritual", "Kitchen", "Event", "Maintenance", "Admin", "Security", "Procurement", "Decoration", "Logistics"];
export const taskPriorities: TaskPriority[] = ["Low", "Medium", "High", "Critical"];
export const taskStatuses: TaskStatus[] = ["Open", "In Progress", "Completed", "Overdue", "Cancelled"];
export const sourceModules: SourceModule[] = ["Event", "Seva", "Darshan", "Kitchen", "Inventory", "Maintenance", "Freelancer", "Manual"];
export const assigneeTypes: AssigneeType[] = ["Employee", "Freelancer", "Volunteer", "Team", "Role"];

// ---- ASSIGNEE POOL (read-only from HR) ----
export const assigneePool = [
  { name: "Pandit Sharma", type: "Employee" as AssigneeType, department: "Rituals" },
  { name: "Head Cook – Team A", type: "Team" as AssigneeType, department: "Kitchen" },
  { name: "Head Cook – Team C", type: "Team" as AssigneeType, department: "Kitchen" },
  { name: "Store Manager", type: "Employee" as AssigneeType, department: "Inventory" },
  { name: "Store Keeper", type: "Employee" as AssigneeType, department: "Inventory" },
  { name: "Temple Attendant", type: "Employee" as AssigneeType, department: "Operations" },
  { name: "Temple Admin", type: "Employee" as AssigneeType, department: "Admin" },
  { name: "Admin Team", type: "Team" as AssigneeType, department: "Admin" },
  { name: "Electrical Team", type: "Team" as AssigneeType, department: "Maintenance" },
  { name: "Maintenance Crew", type: "Team" as AssigneeType, department: "Maintenance" },
  { name: "Safety Officer", type: "Employee" as AssigneeType, department: "Security" },
  { name: "IT Admin", type: "Employee" as AssigneeType, department: "IT" },
  { name: "Counter Staff", type: "Employee" as AssigneeType, department: "Operations" },
  { name: "Pixel Studio", type: "Freelancer" as AssigneeType, department: "Events" },
  { name: "Decor Dreams", type: "Freelancer" as AssigneeType, department: "Events" },
  { name: "Sound Waves Pro", type: "Freelancer" as AssigneeType, department: "Events" },
  { name: "Heritage Electricals", type: "Freelancer" as AssigneeType, department: "Events" },
  { name: "Crowd Control Team (120)", type: "Volunteer" as AssigneeType, department: "Events" },
];

// My tasks = assigned to "Pandit Sharma" or "Temple Admin"
export const myUserId = "Pandit Sharma";
